#!/bin/bash

# setup_nginx_proxy.sh - Script để setup nginx proxy cho domain
# Sử dụng: sudo ./setup_nginx_proxy.sh <domain>

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${BLUE}[NGINX PROXY SETUP]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "Script này cần chạy với quyền root!"
    echo "Sử dụng: sudo $0 <domain>"
    exit 1
fi

# Check if domain parameter is provided
if [ $# -eq 0 ]; then
    print_error "Vui lòng nhập domain name!"
    echo "Sử dụng: sudo $0 <domain>"
    echo "Ví dụ: sudo $0 kd.tiepluatrithuc.com"
    exit 1
fi

DOMAIN=$1
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

print_header "Setup nginx proxy cho domain: ${DOMAIN}"

# Check if nginx is installed
if ! command -v nginx &> /dev/null; then
    print_error "Nginx chưa được cài đặt trên hệ thống!"
    print_status "Đang cài đặt nginx..."
    apt update
    apt install -y nginx
fi

# Check if sites-available directory exists
if [ ! -d "/etc/nginx/sites-available" ]; then
    print_warning "Thư mục sites-available không tồn tại, tạo mới..."
    mkdir -p /etc/nginx/sites-available
    mkdir -p /etc/nginx/sites-enabled
fi

# Generate SSL certificate for the domain if not exists
if [ ! -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
    print_status "Đang tạo SSL certificate cho ${DOMAIN}..."
    
    # Install certbot if not exists
    if ! command -v certbot &> /dev/null; then
        print_status "Đang cài đặt certbot..."
        apt update
        apt install -y certbot python3-certbot-nginx
    fi
    
    # Stop nginx temporarily to use standalone mode
    systemctl stop nginx 2>/dev/null || true
    
    # Get certificate
    if certbot certonly --standalone \
        --non-interactive \
        --agree-tos \
        --register-unsafely-without-email \
        --domains "${DOMAIN}" \
        --keep-until-expiring; then
        print_status "✅ SSL certificate được tạo thành công!"
    else
        print_error "❌ Không thể tạo SSL certificate!"
        print_warning "Sẽ tạo config nginx mà không có SSL"
    fi
    
    # Start nginx back
    systemctl start nginx
fi

# Create nginx config for the domain
print_status "Đang tạo nginx config cho ${DOMAIN}..."

cat > "/etc/nginx/sites-available/${DOMAIN}" << EOF
# Nginx proxy config for ${DOMAIN}
# Generated by setup_nginx_proxy.sh

server {
    listen 80;
    server_name ${DOMAIN};
    
    # Redirect HTTP to HTTPS
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    
    # Include SSL config if exists
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    
    # SSL Settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Security headers
    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Logging
    access_log /var/log/nginx/${DOMAIN}_access.log;
    error_log /var/log/nginx/${DOMAIN}_error.log;

    # Proxy to KD app running on port 1443 (HTTPS)
    location / {
        proxy_pass https://127.0.0.1:1443;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$server_name;
        
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeout settings
        proxy_connect_timeout 30s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
        
        # SSL verification (tắt vì dùng self-signed cert trong Docker)
        proxy_ssl_verify off;
        
        # Buffer settings
        proxy_buffering on;
        proxy_buffer_size 4k;
        proxy_buffers 8 4k;
        proxy_busy_buffers_size 8k;
    }

    # Health check
    location /health {
        proxy_pass https://127.0.0.1:1443/health;
        proxy_ssl_verify off;
        access_log off;
    }

    # Static files optimization
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        proxy_pass https://127.0.0.1:1443;
        proxy_ssl_verify off;
        expires 1y;
        add_header Cache-Control "public, immutable";
        add_header Vary Accept-Encoding;
    }

    # Block access to sensitive files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
EOF

# Enable the site
print_status "Đang enable site ${DOMAIN}..."
if [ -L "/etc/nginx/sites-enabled/${DOMAIN}" ]; then
    print_warning "Site đã được enable trước đó"
else
    ln -s "/etc/nginx/sites-available/${DOMAIN}" "/etc/nginx/sites-enabled/"
fi

# Test nginx configuration
print_status "Đang kiểm tra nginx config..."
if nginx -t; then
    print_status "✅ Nginx config hợp lệ!"
else
    print_error "❌ Nginx config có lỗi!"
    exit 1
fi

# Reload nginx
print_status "Đang reload nginx..."
systemctl reload nginx

# Check if nginx is running
if systemctl is-active --quiet nginx; then
    print_status "✅ Nginx đang chạy!"
else
    print_error "❌ Nginx không chạy!"
    systemctl status nginx
    exit 1
fi

print_status "🎉 Setup hoàn tất!"
echo
echo "=================================="
echo "📋 Thông tin proxy setup:"
echo "=================================="
echo "🌐 Domain: ${DOMAIN}"
echo "🔗 URL: https://${DOMAIN}"
echo "📁 Nginx config: /etc/nginx/sites-available/${DOMAIN}"
echo "📄 Nginx config enabled: /etc/nginx/sites-enabled/${DOMAIN}"
echo "📋 Log files:"
echo "  - Access: /var/log/nginx/${DOMAIN}_access.log"
echo "  - Error: /var/log/nginx/${DOMAIN}_error.log"
echo
echo "📋 Các lệnh hữu ích:"
echo "  - Kiểm tra config: sudo nginx -t"
echo "  - Reload nginx: sudo systemctl reload nginx"
echo "  - Xem logs: sudo tail -f /var/log/nginx/${DOMAIN}_access.log"
echo "  - Disable site: sudo rm /etc/nginx/sites-enabled/${DOMAIN}"
echo
print_status "🚀 Truy cập https://${DOMAIN} để kiểm tra!"

# Setup auto-renewal for SSL
if [ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
    print_status "Đang setup auto-renewal cho SSL certificate..."
    
    # Add cron job if it doesn't exist
    CRON_JOB="0 12 * * * /usr/bin/certbot renew --quiet --post-hook 'systemctl reload nginx'"
    
    if ! crontab -l 2>/dev/null | grep -q "certbot renew"; then
        (crontab -l 2>/dev/null; echo "${CRON_JOB}") | crontab -
        print_status "✅ Auto-renewal đã được thiết lập!"
    else
        print_status "Auto-renewal đã tồn tại"
    fi
fi

print_status "✅ Domain ${DOMAIN} đã sẵn sàng!"